<a href="https://colab.research.google.com/github/kidujm/data_class/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EC%88%98%EC%97%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 사이킷런
## 그 외 파이썬 머신러닝(딥러닝)
- Tensorflow/keras
- pytorch
- Grandint Boosting 계열

# 분류문제
- 분류: 'classification'
- 범주를 예측 ( 어느 범주에 속할지)
- feature : 피쳐. 학습시 사용할 독립변수
- lable : 정답. (범주형)

# 사이킷런 설치
- pip install scikit-learn

In [5]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [7]:
import sklearn

In [8]:
sklearn.__version__

'1.6.1'

# 꽃 데이터 품종(분류) 예측

##  알고리즘 결정트리(DecisionTreeClassifier)
- 여러가지 알고리즘을 모아놓은 것이 사이킷런

In [9]:
# 패키지 로드
from sklearn.datasets import load_iris # 붓꽃데이터
from sklearn.tree import DecisionTreeClassifier # 결정트리 알고리즘
from sklearn.model_selection import train_test_split # 데이터셋 분리

사이킷런의 대표 분류 알고리즘 5가지와 간결한 설명은 다음과 같습니다:

1.  **결정 트리 (Decision Tree)**: 질문을 통해 데이터를 분할하며 분류 규칙을 형성하는, 직관적인 트리 구조 모델입니다.

2.  **서포트 벡터 머신 (Support Vector Machine, SVM)**: 데이터를 가장 잘 나누는 '최적의 결정 경계'를 찾아 분류하는 알고리즘입니다.

3.  **랜덤 포레스트 (Random Forest)**: 여러 개의 결정 트리를 만들어 결과를 종합하여 과적합을 줄이고 예측 성능을 높이는 앙상블 기법입니다.

4.  **K-최근접 이웃 (K-Nearest Neighbors, KNN)**: 새로운 데이터 주변의 가장 가까운 K개 이웃들의 클래스를 참고하여 분류하는 간단한 방식입니다.
거리기반 - 스케일 필수

5.  **로지스틱 회귀 (Logistic Regression)**: 데이터가 특정 클래스에 속할 확률을 예측하여 분류를 수행하는 통계적 모델입니다.

In [10]:
import pandas as pd

iris = load_iris()
df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df_iris['label'] = iris.target
df_iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [11]:
iris.target_names
# 데이터프레임으로 만들기
df_species = pd.DataFrame(data=iris.target_names, columns=['species'])
df_species

      species
0      setosa
1  versicolor
2   virginica

- 머신러닝용 데이터 정제완료

## 데이터셋분리
- 데이터를 학습(80)/ 검증용(20)으로 나눕니다.
- 검증용 데이터의 비율이 일반적으로 20%
- 120(공부)/30(시험)
- train_test_split 패러미터
  * test_size 검증용 데이터 비율(0.2)
  * random_state 시드값. 학습에 일관성 부여.

- x,y -> 피처와 타깃
- x: 피처 :학습용 독립변수
  * X_train : 학습용 피처
  * X_test : 검증용 타깃
  
- y: 타깃(레이블) :정답

In [12]:
df_iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [13]:
# 피쳐와 레이블 나누기
X = df_iris.drop('label', axis=1)
y = df_iris['label']

In [16]:
# 학습용, 검증용 데이터셋 나누기
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=110)

# 학습

In [19]:
# 머신러닝 모델로드
dt = DecisionTreeClassifier()

# 학습
dt.fit(X_train, y_train)

DecisionTreeClassifier()

# 검증
- 검증은 반드시 검증용 데이터(test)를 사용
- 'X_test를 예측한 결과' 와 실제 정답인 'y_test'를 비교해서 채점
-  [predict]             와             [answer]에 각각 위 내용을 저장

In [20]:
dt.predict(X_test)

array([2, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0])

In [ ]:
# 모델이 예측한 값을 데이터프레임에 추가
X_test['predict'] = dt.predict(X_test)

In [23]:
#기존에 존재하던 답을 answer에 추가
X_test['answer'] = y_test
X_test

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),predict,answer
118,7.7,2.6,6.9,2.3,2,2
53,5.5,2.3,4.0,1.3,1,1
25,5.0,3.0,1.6,0.2,0,0
59,5.2,2.7,3.9,1.4,1,1
21,5.1,3.7,1.5,0.4,0,0
81,5.5,2.4,3.7,1.0,1,1
62,6.0,2.2,4.0,1.0,1,1
90,5.5,2.6,4.4,1.2,1,1
97,6.2,2.9,4.3,1.3,1,1
106,4.9,2.5,4.5,1.7,1,2
26,5.0,3.4,1.6,0.4,0,0
134,6.1,2.6,5.6,1.4,2,2
65,6.7,3.1,4.4,1.4,1,1
55,5.7,2.8,4.5,1.3,1,1
148,6.2,3.4,5.4,2.3,2,2
7,5.0,3.4,1.5,0.2,0,0
60,5.0,2.0,3.5,1.0,1,1
84,5.4,3.0,4.5,1.5,1,1
94,5.6,2.7,4.2,1.3,1,1
54,6.5,2.8,4.6,1.5,1,1
42,4.4,3.2,1.3,0.2,0,0
56,6.3,3.3,4.7,1.6,1,1
87,6.3,2.3,4.4,1.3,1,1
14,5.8,4.0,1.2,0.2,0,0
95,5.7,3.0,4.2,1.2,1,1
43,5.0,3.5,1.6,0.6,0,0
28,5.2,3.4,1.4,0.2,0,0
99,5.7,2.8,4.1,1.3,1,1
73,6.1,2.8,4.7,1.2,1,1
22,4.6,3.6,1.0,0.2,0,0

## 정확도 평가
- predict가 실제 answer과 얼마나 일치 하는지.
- accuracy_score 활용

In [24]:
from sklearn.metrics import accuracy_score

In [28]:
#1.
# accuracy_score(y_test,dt.predict(X_test))
#2.
accuracy_score(X_test['answer'],X_test['predict'])

0.9666666666666667

## 교차검증
- 학습데이터에 대해서만 성능이 높은 "과적합"
  * 특히, label 분포가 일정하지 않은 경우 ( 품종 0,1,2의 갯수가 제각각인 경우)
- train/test 분리를 여러번 시도 합니다.
- 비율은 동일하지만, train와 train 에 들어가는 데이터 조합이 다름.

- "최종적으로, 알고리즘을 선택할 때 교차검증 결과를 비교해서 선택"

## 교차검증용 통합 함수 cross_val_score
- 분류, 회귀 모두 사용 가능
- 타깃을 확인하고 적절한 폴드 방식을 선택.(SKfold,kfold)
- 사용할 머신러닝모델, 피쳐,레이블(target)을 전달합니다.
- 추가로 성능지표(ㅇㅇ예, accuracy), 폴드수도 선택 가능.

In [31]:
from sklearn.model_selection import cross_val_score , cross_validate
from sklearn.datasets import load_iris
import numpy as np # numpy import 추가

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=1)

data = iris_data.data # 피처
label = iris_data.target # 레이블

# 성능 지표는 정확도(accuracy) , 교차 검증 세트는 3개
scores = cross_val_score(dt_clf , data , label , scoring='accuracy',cv=5)
#                    알고리즘 , 피쳐 ,레이블, 측정지표명,      폴드 수
print('교차 검증별 정확도:',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.9667 0.9667 0.9    1.     1.    ]
평균 검증 정확도: 0.9667

## 알고리즘 후보 선정 및 교차검증
- 1. 결정트리
- 2. 랜덤포레스트
- 3. 그라디언트 부스팅
-  알고리즘 후보군 설정할 때는 챗봇의 도움을 받아도 됨

In [33]:
# 모델 로드
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [34]:
dt_clf = DecisionTreeClassifier(random_state=1)
rf_clf = RandomForestClassifier(random_state=1)
gb_clf = GradientBoostingClassifier(random_state=1)

In [36]:
# 알고리즘 후보군 전체 교차검증 진행
models = {'결정트리':dt_clf, '랜덤포레스트':rf_clf, '그레이디언트부스팅':gb_clf}

for name, model in models.items():
    scores = cross_val_score(model , data , label , scoring='accuracy',cv=5)


    print(f'모델명:{name}')
    print('교차 검증별 정확도:',np.round(scores, 4))
    print('평균 검증 정확도:', np.round(np.mean(scores), 4))
    print('-'*40)

모델명:결정트리
교차 검증별 정확도: [0.9667 0.9667 0.9    1.     1.    ]
평균 검증 정확도: 0.9667
----------------------------------------
모델명:랜덤포레스트
교차 검증별 정확도: [0.9667 0.9667 0.9333 0.9667 1.    ]
평균 검증 정확도: 0.9667
----------------------------------------
모델명:그레이디언트부스팅
교차 검증별 정확도: [0.9667 0.9667 0.9    0.9667 1.    ]
평균 검증 정확도: 0.96
----------------------------------------

## 하이퍼 파라미터 튜닝 Grid Search CV (선택사항)

In [37]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [38]:
gridcv_dtree = GridSearchCV(dtree, param_grid=parameters, cv=5, refit=True)
gridcv_dtree.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [40]:
scores_df = pd.DataFrame(gridcv_dtree.cv_results_)
scores_df[['params','split0_test_score','split1_test_score','split2_test_score','split3_test_score', 'split4_test_score','mean_test_score','rank_test_score']]

,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,rank_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.666667,0.708333,0.708333,0.708333,0.708333,0.700000,5
1,"{'max_depth': 1, 'min_samples_split': 3}",0.666667,0.708333,0.708333,0.708333,0.708333,0.700000,5
2,"{'max_depth': 2, 'min_samples_split': 2}",0.875000,1.000000,1.000000,1.000000,0.916667,0.958333,3
3,"{'max_depth': 2, 'min_samples_split': 3}",0.875000,1.000000,1.000000,1.000000,0.916667,0.958333,3
4,"{'max_depth': 3, 'min_samples_split': 2}",0.958333,1.000000,1.000000,1.000000,0.916667,0.975000,1
5,"{'max_depth': 3, 'min_samples_split': 3}",0.958333,1.000000,1.000000,1.000000,0.916667,0.975000,1

In [42]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}
gridcv_dtree = GridSearchCV(dtree, param_grid=parameters, cv=5, refit=True)
gridcv_dtree.fit(X_train, y_train)
scores_df = pd.DataFrame(gridcv_dtree.cv_results_)
scores_df[['params','split0_test_score','split1_test_score','split2_test_score','split3_test_score', 'split4_test_score','mean_test_score','rank_test_score']]

,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,rank_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.666667,0.708333,0.708333,0.708333,0.708333,0.700000,5
1,"{'max_depth': 1, 'min_samples_split': 3}",0.666667,0.708333,0.708333,0.708333,0.708333,0.700000,5
2,"{'max_depth': 2, 'min_samples_split': 2}",0.875000,1.000000,1.000000,1.000000,0.916667,0.958333,3
3,"{'max_depth': 2, 'min_samples_split': 3}",0.875000,1.000000,1.000000,1.000000,0.916667,0.958333,3
4,"{'max_depth': 3, 'min_samples_split': 2}",0.958333,1.000000,1.000000,1.000000,0.916667,0.975000,1
5,"{'max_depth': 3, 'min_samples_split': 3}",0.958333,1.000000,1.000000,1.000000,0.916667,0.975000,1

In [43]:
# iris 데이터 150개 전체 학습 후 model에 저장
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [45]:
df_iris
# 모델은 결정트리로 결정
df = DecisionTreeClassifier()

# 피쳐 X, 레이블 y
X = df_iris.drop('label', axis=1)
y = df_iris['label']

# 학습
dt.fit(X,y)

DecisionTreeClassifier()

In [46]:
# iris 데이터 150 개 전체 학습 후 model에 저장
df_iris
# 모델은 결정트리로 결정.
dt = DecisionTreeClassifier()

# 피쳐 X, 레이블 y
X = df_iris.drop('label', axis=1)
y = df_iris['label']

# 학습
dt.fit(X, y)

DecisionTreeClassifier()

In [49]:
# 모델저장
import pickle
with open('dt_iris_model.pkl', 'wb') as f: pickle.dump(dt, f)

In [51]:
import pandas as pd

In [53]:
book = pd.read_csv('도서데이터_정제완료_대출범주_추가.csv')
book

,no,랭킹,도서명,지은이,출판사,출판연도,isbn13_도서고유번호,부가기호,분류기호,공식분류,...,최다연령대_남성,성비_여성,20~30대_남성,20~30대_여성,알라딘_분류,단행/시리즈,공식중분류,공식소분류,키워드,대출(범주)
0,1,1,소년이 온다 :한강 장편소설,지은이: 한강,창비,2014,9788936434120,A03810,813.62,문학 > 한국문학 > 소설,...,40.0,0.7,8.3,31.4,한국소설,단행본,한국문학,소설,"[""저항"", ""증언"", ""폭력"", ""기억"", ""연대""]",2
1,2,2,홍학의 자리 :정해연 장편소설,지은이: 정해연,문학동네,2021,9788954681155,A03810,813.70,문학 > 한국문학 > 소설,...,20.0,0.8,9.9,48.6,추리/미스터리소설,단행본,한국문학,소설,"[""로맨스"", ""사랑"", ""이별"", ""가족"", ""상처""]",2
2,3,3,작별하지 않는다 :한강 장편소설,지은이: 한강,문학동네,2021,9788954682152,A03810,813.62,문학 > 한국문학 > 소설,...,50.0,0.7,7.8,25.1,한국소설,단행본,한국문학,소설,"[""가족"", ""이별"", ""시간"", ""기억""]",2
3,4,4,모순 :양귀자 장편소설,지은이: 양귀자,쓰다,2013,9788998441012,A03810,813.62,문학 > 한국문학 > 소설,...,30.0,0.8,9.4,54.5,한국소설,단행본,한국문학,소설,"[""성장"", ""사랑"", ""인간관계"", ""가족"", ""상실""]",2
4,5,5,나는 소망한다 내게 금지된 것을 :양귀자 장편소설,지은이: 양귀자,쓰다,2019,9788998441074,A03810,813.62,문학 > 한국문학 > 소설,...,20.0,0.9,4.2,76.5,한국소설,단행본,한국문학,소설,"[""사랑"", ""금지"", ""욕망"", ""성장"", ""성찰""]",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3681,4994,4972,오늘은 어떤 낱말을 건져 볼까?,키아라 소렌티노 글 ;서남희 옮김,피카주니어,2024,9791192869193,A77880,883.00,문학 > 이탈리아문학 > 소설,...,40.0,0.9,0.0,43.0,그림책,단행본,이탈리아문학,소설,"[""판타지"", ""모험"", ""우정"", ""성장"", ""마법""]",0
3682,4996,4995,까만 토끼,필리파 레더스 글·그림 ;최지현 옮김,알에이치코리아,2013,9788925550459,A73840,843.00,문학 > 영미문학 > 소설,...,30.0,0.9,6.4,46.2,그림책,단행본,영미문학,소설,"[""동화"", ""교훈"", ""우정"", ""성장"", ""모험""]",0
3683,4997,4995,오싹오싹 좀비 금붕어,글: 모 오하라 ;번역: 지혜연,예림당,2022,9788930264914,A74840,843.00,문학 > 영미문학 > 소설,...,40.0,0.9,0.9,14.3,동화/명작/고전,시리즈,영미문학,소설,"[""공포"", ""좀비"", ""금붕어"", ""스릴러"", ""괴기""]",0
3684,4998,4995,봄이 오리,지은이: 한연진,보림출판사,2025,9788943317799,A77810,813.70,문학 > 한국문학 > 소설,...,30.0,0.8,8.6,30.9,그림책,단행본,한국문학,소설,"[""힐링"", ""성장"", ""우정"", ""용기""]",0
3685,4999,4995,"아빠, 나한테 물어봐",버나드 와버 글 ;이수지 그림·옮김,비룡소,2015,9788949113609,A74800,843.00,문학 > 영미문학 > 소설,...,40.0,0.9,4.8,40.3,그림책,시리즈,영미문학,소설,"[""성장"", ""관계"", ""가족"", ""이별"", ""사랑""]",0