<a href="https://colab.research.google.com/github/kidujm/data_class/blob/main/%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* 협업필터링
  * 유저ID, 컨텐츠ID, 평가(예,별점)

In [3]:
! pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 4.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp312-cp312-linux_x86_64.whl size=2554979 sha256=190c3479c22d5f10247519b4ddb20b93b561ade3b69f6d76f753957975ac0e7e
  Stored in directory: /root/.cache/pip/wheels/75/fa/bc/739bc2cb1fbaab6061854e6cfbb81a0ae52c92a502a7fa454b
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

# 다운그레이드

In [4]:
pip install numpy==1.26.4

Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.7 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 78.1 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [3]:
# 영화 데이터
from surprise import Dataset
import pandas as pd

data = Dataset.load_builtin('ml-100k')
df = pd.DataFrame(data.raw_ratings)
df

Dataset ml-100k could not be found. Do you want to download it? [Y/n] ㅛ
Dataset ml-100k could not be found. Do you want to download it? [Y/n] y
Trying to download dataset from https://files.grouplens.org/datasets/movielens/ml-100k.zip...
Done! Dataset ml-100k has been saved to /root/.surprise_data/ml-100k

         0     1    2          3
0      196   242  3.0  881250949
1      186   302  3.0  891717742
2       22   377  1.0  878887116
3      244    51  2.0  880606923
4      166   346  1.0  886397596
...    ...   ...  ...        ...
99995  880   476  3.0  880175444
99996  716   204  5.0  879795543
99997  276  1090  1.0  874795795
99998   13   225  2.0  882399156
99999   12   203  3.0  879959583

[100000 rows x 4 columns]

In [4]:
## 필요없는 열 미리 제거
df.drop([3], axis=1, inplace=True)
df

         0     1    2
0      196   242  3.0
1      186   302  3.0
2       22   377  1.0
3      244    51  2.0
4      166   346  1.0
...    ...   ...  ...
99995  880   476  3.0
99996  716   204  5.0
99997  276  1090  1.0
99998   13   225  2.0
99999   12   203  3.0

[100000 rows x 3 columns]

In [5]:
from surprise.model_selection import train_test_split
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

from surprise import accuracy
from surprise import SVD
# 학습 및 검증
# 알고리즘 선택 및 학습 (SVD 사용)
algo = SVD()
algo.fit(trainset)

# 테스트셋에 대한 예측 및 성능 평가
pred = algo.test(testset) # 예측
rmse = accuracy.rmse(pred) # 평가

RMSE: 0.9358

In [6]:
df.describe()

                   2
count  100000.000000
mean        3.529860
std         1.125674
min         1.000000
25%         3.000000
50%         4.000000
75%         4.000000
max         5.000000

In [7]:
pred[:5]

[Prediction(uid='907', iid='143', r_ui=5.0, est=4.663990300671177, details={'was_impossible': False}),
 Prediction(uid='371', iid='210', r_ui=4.0, est=4.283129439056973, details={'was_impossible': False}),
 Prediction(uid='218', iid='42', r_ui=4.0, est=3.5161439725605175, details={'was_impossible': False}),
 Prediction(uid='829', iid='170', r_ui=4.0, est=4.091854675642232, details={'was_impossible': False}),
 Prediction(uid='733', iid='277', r_ui=1.0, est=2.7527484179343102, details={'was_impossible': False})]

In [8]:
uid = str(196)
iid = str(302)
pred = algo.predict(uid, iid)
pred

Prediction(uid='196', iid='302', r_ui=None, est=4.11575167011827, details={'was_impossible': False})

In [1]:
import pandas as pd
movies = pd.read_csv('u.item', sep='|', header=None, encoding='latin-1')

In [10]:
movies

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
recommend_movies('244')

   iid       est                             title
0  127  5.000000             Godfather, The (1972)
1   98  4.899550  Silence of the Lambs, The (1991)
2   14  4.837439                Postino, Il (1994)
3  137  4.833079                  Big Night (1996)
4  408  4.788041             Close Shave, A (1995)
5  483  4.781859                 Casablanca (1942)
6  285  4.775714             Secrets & Lies (1996)
7  923  4.712752      Raise the Red Lantern (1991)
8   12  4.689072        Usual Suspects, The (1995)
9  513  4.667926             Third Man, The (1949)

In [2]:
def recommend_movies(user_id):
    # 전체 아이템(영화) 목록
    all_items = set(df[1].unique())

    # 유저가 이미 평점을 준 아이템 목록
    user_items = set(df[df[0] == user_id][1])

    # 평점을 주지 않은 아이템 목록
    unrated = all_items - user_items

    # 예측 수행
    predictions = [algo.predict(user_id, iid) for iid in unrated]
    predictions = pd.DataFrame(predictions)

    # 추천 점수 테이블
    추천 = predictions[['iid', 'est']]

    # 점수 기준 정렬
    정렬 = 추천.sort_values('est', ascending=False).reset_index(drop=True)

    # 영화 제목 매핑 테이블
    movies.rename(columns={0: 'iid', 1: 'title'}, inplace=True)
    맵핑테이블 = movies.groupby('iid')['title'].first()

    # iid 타입 맞추기
    정렬['iid'] = 정렬['iid'].astype(int)

    # 제목 매핑
    정렬['title'] = 정렬['iid'].map(맵핑테이블)

    # 상위 10개 반환
    return 정렬.head(10)